// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyBuys.PLUImportWS.Services;

#nullable disable

namespace SkyBuys.PLUImportWS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220921205937_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SkyBuys.Models.ItemDefinition", b =>
                {
                    b.Property<long>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecId"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ItemSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecId");

                    b.ToTable("itemDefinitions");

                    b.HasData(
                        new
                        {
                            RecId = -1L,
                            Brand = "BRAND",
                            ItemNumber = "ITM1",
                            ItemSize = "SIZE",
                            LongDescription = "TEST ITEM SHORT DESCRIPTION",
                            MainCategory = "MAIN CATEGORY",
                            ShortDescription = "TEST ITEM 1",
                            SubCategory = "SUB CATEGORY"
                        });
                });

            modelBuilder.Entity("SkyBuys.Models.Soh", b =>
                {
                    b.Property<long>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecId"), 1L, 1);

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrimaryQuantity")
                        .HasColumnType("float");

                    b.Property<string>("SubinventoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecId");

                    b.ToTable("Soh");

                    b.HasData(
                        new
                        {
                            RecId = -1L,
                            ItemNumber = "1111111",
                            OrganizationCode = "NADAPR",
                            PrimaryQuantity = 10.0,
                            SubinventoryCode = "NAD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
